
package org.example.customerservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.example.customer.AccountType;
import org.example.customer.CustomerType;
import org.example.customer.Statement;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://www.example.org/CustomerService/")
@XmlSeeAlso({
    org.example.customer.ObjectFactory.class,
    org.example.customerservice.ObjectFactory.class
})
public interface CustomerService {


    /**
     * 
     * @param customerId
     * @param name
     * @return
     *     returns org.example.customer.CustomerType
     */
    @WebMethod(action = "http://www.example.org/CustomerService/getCustomer")
    @WebResult(name = "customer", targetNamespace = "")
    @RequestWrapper(localName = "getCustomer", targetNamespace = "http://www.example.org/CustomerService/", className = "org.example.customerservice.GetCustomer")
    @ResponseWrapper(localName = "getCustomerResponse", targetNamespace = "http://www.example.org/CustomerService/", className = "org.example.customerservice.GetCustomerResponse")
    public CustomerType getCustomer(
        @WebParam(name = "customerId", targetNamespace = "")
        String customerId,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param accountId
     * @param accountNumber
     * @param sortCode
     * @return
     *     returns org.example.customer.AccountType
     */
    @WebMethod(action = "http://www.example.org/CustomerService/getAccounts")
    @WebResult(name = "accounts", targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://www.example.org/CustomerService/", className = "org.example.customerservice.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://www.example.org/CustomerService/", className = "org.example.customerservice.GetAccountsResponse")
    public AccountType getAccounts(
        @WebParam(name = "accountNumber", targetNamespace = "")
        String accountNumber,
        @WebParam(name = "sortCode", targetNamespace = "")
        String sortCode,
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId);

    /**
     * 
     * @param accountId
     * @return
     *     returns org.example.customer.Statement
     */
    @WebMethod(action = "http://www.example.org/CustomerService/getTransactions")
    @WebResult(name = "statement", targetNamespace = "http://www.example.org/Customer")
    @RequestWrapper(localName = "getTransactions", targetNamespace = "http://www.example.org/CustomerService/", className = "org.example.customerservice.GetTransactions")
    @ResponseWrapper(localName = "getTransactionsResponse", targetNamespace = "http://www.example.org/CustomerService/", className = "org.example.customerservice.GetTransactionsResponse")
    public Statement getTransactions(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId);

}
